local Item = require("src/item")
local GildedRose = require("src/gilded_rose")

describe("Gilded Rose", function()
  it("should foo", function()
    local gilded_rose = GildedRose:new({ Item:new("foo", 0, 0) })
    local items = gilded_rose:updateQuality()
    assert.same("fixme", items[1].name)
  end)
end)
