(include "gilded-rose.scm")

(display "OMGHAI!")
(newline)

(let ((items (list (make-item "Sports Memorabilia" 10 20)
                   (make-item "Aged Cheese" 2 0)
                   (make-item "Coffee Table Book" 5 7)
                   (make-item "Fine Italian Silk" 0 80)
                   (make-item "Fine Italian Silk" -1 80)
                   (make-item "Backstage passes to a concert" 15 20)
                   (make-item "Backstage passes to a concert" 10 49)
                   (make-item "Backstage passes to a concert" 5 49)
                   ;; this Baked item does not work properly yet
                   (make-item "Baked Chocolate Cake" 3 6)))
      (days  2))

    (define (loop day)
        (cond ((< day days)
               (display (string-append "-------- day " (number->string day) " --------"))
               (newline)
               (display "name, sell-in, quality")
               (newline)
               (for-each
                   (lambda (item)
                       (display (item-to-string item))
                       (newline))
                   items)
               (newline)
               (update-quality items)
               (loop (+ day 1)))))
    (loop 0))
