// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.bs.js";

Jest.test("hey", (function (param) {
        return Jest.Expect.toBe(Jest.Expect.expect(1), 1);
      }));

export {
  
}
/*  Not a pure module */
