// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var GildedRose = require("./GildedRose.bs.js");

Jest.describe("Gilded Rose", (function (param) {
        Jest.test("should foo", (function (param) {
                var items = [{
                    name: "foo",
                    sellIn: 0,
                    quality: 0
                  }];
                var updatedItems = GildedRose.updateQuality(items);
                return Jest.Expect.toBe(Jest.Expect.expect(Caml_array.get(updatedItems, 0).name), "fixme");
              }));
      }));

/*  Not a pure module */
